name: Validate Pull Request

on:
  workflow_dispatch:
  push:
    branches: [ 'feature/*', 'master' ]
  pull_request:
    branches: [ 'feature/*', 'master' ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NUGET_URL: https://nuget.pkg.github.com/microsoft/index.json
      GRAPH_NUGET_URL: https://nuget.pkg.github.com/microsoftgraph/index.json
      solutionName: Microsoft.Graph.Beta.sln
    steps:
      - uses: actions/checkout@v2.4.0
      - name: Setup .NET
        uses: actions/setup-dotnet@v1.9.0
        with:
          dotnet-version: 6.0.x
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: csharp
      - name: Add NuGet kiota source
        run: |
          dotnet nuget add source ${{env.NUGET_URL}} -n ReadKiotaGithubPackages -u ${{secrets.PUBLISH_GH_USERNAME}} -p ${{secrets.PUBLISH_GH_TOKEN}} --store-password-in-clear-text
      - name: Add Graph Core source
        run: |
          dotnet nuget add source ${{env.GRAPH_NUGET_URL}} -n ReadGithubPackages -u ${{secrets.PUBLISH_GH_USERNAME}} -p ${{secrets.PUBLISH_GH_TOKEN}} --store-password-in-clear-text
      - name: Restore dependencies
        run: dotnet restore ${{ env.solutionName }}
      - name: Build
        run: dotnet build ${{ env.solutionName }} --no-restore -c Release /p:UseSharedCompilation=false
      - name: Test
        run: dotnet test ${{ env.solutionName }} --no-build --verbosity normal -c Release /p:CollectCoverage=true /p:CoverletOutput=TestResults/ /p:CoverletOutputFormat=opencover
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1
